### ISSUE TITLE
Can't get react-redux/react-router to use hot-reloaded module

### ISSUE THREAD

**Issue by clintharris** [sormy/systemjs-hot-reloader#1]
I would love to use this on my project! Unfortunately, everything seems to be working _except_ the reloaded module isn't being used for some reason...

For example:
- I edit my component (`FooComponent.js`)
- The browser is notified of the change, and hot-reloader debug output shows:

```
Reloading file: js/views/FooComponent.js
HotReloader.js:17 Reloading module: http://localhost:8080/js/views/FooComponent.js
HotReloader.js:17 Removing 2 module(s): http://localhost:8080/js/views/FooComponent.js, http://localhost:8080/js/app.js
HotReloader.js:17 Importing root module: http://localhost:8080/js/app.js
```
- Browser makes xhr requests for the 3 files and I see that the returned `FooComponent.js` is correct (i.e., has my latest changes).
- Updated `console.log()` statements in `FooComponent.js` run an show the correct/updated output in console (i.e., I know the browser is interpreting the latest version of the code).
- _Problem_: `FooComponent.render()` output doesn't reflect latest changes. Further, `console.log()` statements aren't updated either. SystemJS is clearly using the old module.

I _suspect_ the problem is somehow related to `react-redux` or `react-router` (see `app.js` below). Any ideas or suggestions? Thanks!

app.js:

```
...
import { createStore, applyMiddleware } from 'redux';
import {Provider} from 'react-redux';
import thunk from 'redux-thunk';
import createLogger from 'redux-logger';
import {Router, Route} from 'react-router';
import { syncHistoryWithStore, routerReducer, routerMiddleware } from 'react-router-redux';
import { useRouterHistory } from 'react-router';
import { createHistory } from 'history';

import FooComponent from './views/FooComponent';

const routerHistory = useRouterHistory(createHistory)({...});

const createStoreWithMiddleware = applyMiddleware(
  thunk,
  createLogger(),
  routerMiddleware(routerHistory)
)(createStore);

let store = createStoreWithMiddleware(myReduxReducers);

ReactDOM.render(
  (<Provider store={store}>
    <Router history={history}>
      <Route path="/" component={Main}>
        <Route path="foo" component={FooComponent}></Route>
      </Route>
    </Router>
  </Provider>),
  document.getElementById('app')
);
```

**Comment by sormy** [comment]
I have a new version and will release it soon. It is complete rewrite.

**Comment by sormy** [comment]
Please try with new `systemjs-hot-reloader` v2.x and `bs-systemjs-hot-reloader` and let me know how does it work.

**Comment by clintharris** [comment]
Have been trying the new stuff per your suggestion. This is all I see in the log when I edit `FooComponent.js` for example:

```
[HMR] Reloading file: js/views/FooComponent.js
SystemHotReloader.js:37 [HMR] Nothing to update
```

`FooComponent.render()` is not being called.

I have wrapped the entire app in `<AppContainer>` per `react-hot-loader` 3.x. Also, I have added the `__reload()` method per your docs; it is not being called.

Here is roughly what `app.js` looks like now:

```
import 'react-hot-loader/lib/patch.dev.js';
import AppContainer from 'react-hot-loader/lib/AppContainer.dev.js';

ReactDOM.render(
  (<AppContainer><Provider store={store}>
    <Router history={history}>
      <Route path="/" component={Main}>
        <Route path="foo" component={FooComponent}></Route>
      </Route>
    </Router>
  </Provider></AppContainer>),
  document.getElementById('app')
);

export function __reload() {
  console.log('__reload() was called');
  // makes same ReactDOM.render() call as above
}
```

My `index.html` is starting up with SystemJS like this:

```
    SystemJS.import('systemjs-hot-reloader-ex')
      .then(function (exports) {
        exports.default.logLevel = 3;
      })
      .then(System.import('js/app'))
      .catch(function(error) {
        console.error(error);
      });
```

**Comment by clintharris** [comment]
I suspect that my problem is due to _not_ using `react-hot-loader/babel`.

When my source file is edited, gulp is using babel to transpile the code and then copy it to another folder. _Then_ browsersync pushes the already-transpiled file to the browser. So it is not going through the `react-hot-loader/babel`

**Comment by clintharris** [comment]
I modified my gulp-driven babel config to include the `react-hot-loader/babel` plugin. This means that after transpilation, `FooComponent.js` now has the following code at the end:

```
var _temp = function () {

  if (typeof __REACT_HOT_LOADER__ === 'undefined') {
    return;
  }

  __REACT_HOT_LOADER__.register(FooComponent, 'FooComponent', '/path/to/js/views/FooComponent.js');

}();
```

The problem is `FooComponent.js` is getting evaluated _before_ `patch.dev.js`. So `__REACT_HOT_LOADER__` is `undefined` when `_temp()` runs; nothing is registered with react-hot-reloader.

`patch.dev.js` is getting loaded and evaluated, but too late, even though I have `import 'react-hot-loader/lib/patch.dev.js'` on the first line in my `app.js`.

**Comment by sormy** [comment]
I will publish today evening after work full working skeleton.

**Comment by clintharris** [comment]
The previous issue with `__REACT_HOT_LOADER__` being undefined was happening because I had Babel configured to run code through the SystemJS plugin _before_ the react-hot-loader/babel plugin. Changing the order to this fixed the problem:

```
{
  presets: ['es2015', 'stage-2', 'react'],
  "plugins": ["react-hot-loader/babel", "transform-es2015-modules-systemjs"]
}
```

Now the `_temp()` function is _correctly_ placed _inside_ the `execute()` method of my transpiled SystemJS module.

**Comment by clintharris** [comment]
The (hopefully last) issue is that `SystemJSLoader` has my module registered at `http://localhost:9000/js/views/FooComponent.js`

However, `SystemHotReloader` is looking for this (invalid) path: `http://localhost:9000/dist/js/views/FooComponent.js`

In other words, `/dist/` is added to the URL and breaks things. This is happening because I have bsSystemHotReloader watching the `dist/*` folder for changes:

```
_browserSync.use(bsSystemHotReloader, { cssReloader: false, files: ['./dist/js/**/*.js'] });
```

**Comment by clintharris** [comment]
Finally got it working! I'm getting around the previously-mentioned path issue by manually emitting the `file:changed` event with a modified path that works with SystemJS:

```
_browserSync.use(bsSystemHotReloader, { cssReloader: false, files: [] });
gulp.watch(...)
  .on('change', function(event) {
    var systemJsFriendlyPath = ... // Do stuff with event.path
    _browserSync.emitter.emit('file:changed', { path: systemJsFriendlyPath, namespace: bsSystemHotReloader['plugin:name'] });
  });
```

Would be nice if the bs-systemjs-hot-reloader exposed a hook for transforming the path like this.

**Comment by sormy** [comment]
I would like to fix this issue but I have a few questions:

1) Why do you have source files in `dist` folder which is most likely used as build result.
2) Why do you have `dist` mapped to `/` in `jspm.cofig.js`? How did you do that?

This reloader designed to use default project layout, so project root should be on the same level with `jspm_packages`:
- /jspm_packages
- /jspm.config.js
- /index.html
- /src/index.js

PS: I feel that if you move store into separate module to export store instance as module exports, then you don't need `react-hot-loader`, babel plugin, react patch and `__reload()` hook, standard module reload will be enough because in that case store module will be reloaded only if you will modify store module.

**Comment by sormy** [comment]
I modified `bs-systemjs-hot-reloader` based on your feedback. Now it has `resolver()` option.
Also I pushed featured skeleton demo here: https://github.com/sormy/jspm-hot-skeleton.git

**Comment by clintharris** [comment]
I know...the folder structure seems silly. Stuck with it for now.

Thank you for adding the custom `resolve` option and the great demo/skeleton app . I have updated to the latest version of `bs-systemjs-hot-reloader` and `systemjs-hot-reloader-ex`, and everything works great!

**Comment by sormy** [comment]
ok, good, i'm closing issue
